spring:
  application:
    name: basic
  cloud:
    config:
      #uri:  http://localhost:7001/
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: config-server
  rabbitmq:
    host: 192.168.31.54
    port: 5672
    username: admin
    password: admin
server:
  port: 7002
  eureka:
    instance:
      prefer-ip-address: true # 注册服务的时候使用服务的ip地址
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
content: contents
